module.exports = {
  apps: [
    {
      name: 'relmdesk-backend',
      cwd: '/home/ubuntu/HelmDesk/backend',
      script: 'src/server.js',
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_NAME: 'relmdesk',
        DB_USER: 'relmdesk_user',
        DB_PASSWORD: 'relmdesk_pass_2024',
        JWT_SECRET: 'relmdesk_jwt_secret_super_secure_2024_bikes_relm',
        JWT_EXPIRES_IN: '7d',
        FRONTEND_URL: 'http://177.153.39.134:3000',
        APP_URL: 'http://177.153.39.134:3000',
        MAX_FILE_SIZE: 15728640,
      },
      watch: false,
      max_memory_restart: '512M',
      log_file: '/var/log/relmdesk/backend.log',
      error_file: '/var/log/relmdesk/backend-error.log',
      out_file: '/var/log/relmdesk/backend-out.log',
      restart_delay: 3000,
      autorestart: true,
    },
  ],
};
